Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/focal64"

  config.vm.synced_folder "../projects/", "/home/vagrant/projects/", fsnotify: true

  config.vm.define "nodejs-18"
  config.vm.provider :virtualbox do |vb|
    vb.name = "nodejs-18"
  end
  config.vm.hostname = "nodejs-18"

  config.vm.provision "shell", inline: <<-SHELL
    sudo apt-get update

    sudo apt-get install -y ca-certificates curl gnupg
    sudo mkdir -p /etc/apt/keyrings
    curl -fsSL https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key | sudo gpg --dearmor -o /etc/apt/keyrings/nodesource.gpg

    NODE_MAJOR=18
    echo "deb [signed-by=/etc/apt/keyrings/nodesource.gpg] https://deb.nodesource.com/node_$NODE_MAJOR.x nodistro main" | sudo tee /etc/apt/sources.list.d/nodesource.list

    sudo apt-get update
    sudo apt-get install nodejs -y
    node -v

    sudo npm install --global yarn
    yarn --version
  SHELL

  config.vm.network "private_network", type: "dhcp", name: "vboxnet0"
end
